/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskwebappwsclient;

import java.util.List;
import javax.swing.JOptionPane;
import org.me.people.PersonData;

/**
 *
 * @author Iwa Stojnowa
 */
public class PersonListDialog extends javax.swing.JDialog {
    private String[] tableColumnNames;
    private Object[][] tableData;
    private List<PersonData> personDataList;
    private Integer indexOfSelectedItem = null;
    private boolean hideCancelButton;

    /**
     * Creates new form PersonListDialog
     */
    public PersonListDialog(java.awt.Frame parent, boolean modal, List<PersonData> personDataList, boolean hideCancelButton) {
        super(parent, modal);        
        this.hideCancelButton = hideCancelButton;
        this.personDataList = personDataList;
        initComponents();
        tableColumnNames = new String[] {"Full name", "PIN", "Email"};
        tableData = new Object[personDataList.size()][3];
        int i=0;
        for (PersonData personData : personDataList) {
            tableData[i][0] = personData.getFULLNAME();
            tableData[i][1] = personData.getPIN();
            tableData[i][0] = personData.getEMAIL();
            i++;            
        }
        personDataTable.setModel(new CustomTableModel(tableData, tableColumnNames));
        if(hideCancelButton){
            cancelButton.setVisible(false);
            personDataTable.setRowSelectionAllowed(false);
        }        
    }

    public Integer showDialog() {
        setVisible(true);
        return indexOfSelectedItem;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personDataTable = new javax.swing.JTable();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Persons matching search criteria:");

        personDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(personDataTable);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(!hideCancelButton) {
            if(personDataTable.getSelectedRow() != -1) {
                indexOfSelectedItem = personDataTable.getSelectedRow();
                setVisible(false);
                dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select a person first");
            }
        }
        else {
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        indexOfSelectedItem = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTable personDataTable;
    // End of variables declaration//GEN-END:variables
}